package ast;

public enum NodeKind {
  EXPRESSION, ASIGN, DEC, DECARRAY, INPUT,PRINT, IFELSE, ELSIF, WHILE, BREAK, MEMSPACE, FREE,
  FOR, TIPO, BLOQUE, FUNCIONCALL, FUNCIONDEC, PARAM, STRUCT, RETURN,
  CASE, DEFCASE, SWITCH, MAIN, PROGRAMA, BLOQUEDEF, GLOBVAR, CONSTANTE
}
