
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Wed Mar 22 18:10:39 CET 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 13;
  public static final int POT = 10;
  public static final int LLCIERRE = 28;
  public static final int POR = 8;
  public static final int CCIERRE = 49;
  public static final int PCIERRE = 21;
  public static final int ELSIF = 31;
  public static final int INPUT = 45;
  public static final int CASE = 34;
  public static final int CAP = 48;
  public static final int INT = 40;
  public static final int PRINTLN = 44;
  public static final int FOR = 23;
  public static final int NOT = 5;
  public static final int AND = 4;
  public static final int IGUAL = 18;
  public static final int LLAP = 27;
  public static final int OR = 3;
  public static final int BOOL = 42;
  public static final int DIV = 9;
  public static final int MAYIGUAL = 17;
  public static final int MAIN = 46;
  public static final int IF = 30;
  public static final int PTOCOMA = 29;
  public static final int IGDOBLE = 12;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int COMA = 19;
  public static final int MENOS = 7;
  public static final int MENOR = 14;
  public static final int MOD = 11;
  public static final int BREAK = 36;
  public static final int VOID = 24;
  public static final int SWITCH = 33;
  public static final int REAL = 54;
  public static final int MAYOR = 15;
  public static final int ENT = 53;
  public static final int PAP = 20;
  public static final int FLECHA = 50;
  public static final int DOSPTOS = 37;
  public static final int ELSE = 32;
  public static final int IDEN = 2;
  public static final int BB = 47;
  public static final int WHILE = 22;
  public static final int MENIGUAL = 16;
  public static final int DEFAULT = 35;
  public static final int FLOAT = 41;
  public static final int FALSE = 52;
  public static final int STRUCT = 26;
  public static final int MEMSPACE = 38;
  public static final int PRINT = 43;
  public static final int FREE = 39;
  public static final int MAS = 6;
}

