
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 04 10:13:38 CEST 2023
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 12;
  public static final int POT = 9;
  public static final int LLCIERRE = 27;
  public static final int POR = 7;
  public static final int CCIERRE = 47;
  public static final int PCIERRE = 20;
  public static final int ELSIF = 30;
  public static final int INPUT = 43;
  public static final int CASE = 33;
  public static final int CAP = 46;
  public static final int INT = 38;
  public static final int PRINTLN = 42;
  public static final int FOR = 22;
  public static final int NOT = 4;
  public static final int AND = 3;
  public static final int IGUAL = 17;
  public static final int LLAP = 26;
  public static final int OR = 2;
  public static final int BOOL = 40;
  public static final int DIV = 8;
  public static final int MAYIGUAL = 16;
  public static final int MAIN = 44;
  public static final int IF = 29;
  public static final int PTOCOMA = 28;
  public static final int IGDOBLE = 11;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int TRUE = 49;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int MENOS = 6;
  public static final int MENOR = 13;
  public static final int MOD = 10;
  public static final int BREAK = 35;
  public static final int VOID = 23;
  public static final int SWITCH = 32;
  public static final int REAL = 52;
  public static final int MAYOR = 14;
  public static final int ENT = 51;
  public static final int PAP = 19;
  public static final int FLECHA = 48;
  public static final int ELSE = 31;
  public static final int IDEN = 53;
  public static final int BB = 45;
  public static final int WHILE = 21;
  public static final int MENIGUAL = 15;
  public static final int DEFAULT = 34;
  public static final int FLOAT = 39;
  public static final int FALSE = 50;
  public static final int STRUCT = 25;
  public static final int MEMSPACE = 36;
  public static final int PRINT = 41;
  public static final int FREE = 37;
  public static final int MAS = 5;
}

